import { useState } from 'react'
import { AlertTriangle, ArrowRight, CalendarDays, ChevronDown, MapPin, Plane, TicketCheck, UserRound } from 'lucide-react'
import { Link, Navigate, useLocation } from 'react-router-dom'
import { useApp } from '../context/AppContext'

export default function BookingsPage() {
  const { user, bookings, cancelBooking } = useApp()
  const location = useLocation()
  const [open, setOpen] = useState(bookings[0]?.id || null)
  if (!user) return <Navigate to="/login" state={{ from: location.pathname }} replace />
  return <main className="bookings-page"><section className="subpage-hero bookings-hero"><div className="page-width"><span className="overline">YOUR JOURNEYS</span><h1>My bookings</h1><p>Everything you need before the boarding call.</p></div></section><section className="bookings-content page-width"><div className="bookings-heading"><div><span className="overline coral">UPCOMING & PAST</span><h2>{bookings.length} booking{bookings.length !== 1 ? 's' : ''}</h2></div><Link to="/">Book another flight <ArrowRight /></Link></div>{bookings.length ? <div className="booking-list">{bookings.map((booking) => <article className={booking.status === 'Cancelled' ? 'booking-card cancelled' : 'booking-card'} key={booking.id}><button className="booking-summary" onClick={() => setOpen(open === booking.id ? null : booking.id)}><span className="booking-status"><i /> {booking.status}</span><div className="booking-route"><strong>{booking.from}</strong><span><Plane /><small>{booking.airline}</small></span><strong>{booking.to}</strong></div><div className="booking-date"><CalendarDays /><span><strong>{new Date(`${booking.date}T12:00:00`).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}</strong><small>{booking.depart}–{booking.arrive}</small></span></div><ChevronDown className={open === booking.id ? 'up' : ''} /></button>{open === booking.id && <div className="booking-details"><div><span><TicketCheck /> Booking reference</span><strong>{booking.id}</strong></div><div><span><UserRound /> Passenger</span><strong>{booking.passenger}</strong></div><div><span><MapPin /> Seat & terminal</span><strong>{booking.seat || 'Auto'} · {booking.terminal || 'TBD'}</strong></div><div><span>Total paid</span><strong>₹{booking.total.toLocaleString('en-IN')}</strong></div>{booking.status !== 'Cancelled' && <button onClick={() => cancelBooking(booking.id)}><AlertTriangle /> Cancel demo booking</button>}</div>}</article>)}</div> : <div className="empty-panel large"><TicketCheck /><h2>No journeys yet</h2><p>Once you complete the demo checkout, your itinerary will appear here.</p><Link to="/">Search flights</Link></div>}</section></main>
}
