import { ArrowRight, Heart, MapPin, Settings, ShieldCheck, TicketCheck, UserRound } from 'lucide-react'
import { Link, Navigate, useLocation } from 'react-router-dom'
import { useApp } from '../context/AppContext'

export default function ProfilePage() {
  const { user, bookings, saved, flights } = useApp()
  const location = useLocation()
  if (!user) return <Navigate to="/login" state={{ from: location.pathname }} replace />
  const savedFlights = flights.filter((item) => saved.includes(item.id))
  return <main className="account-page"><section className="account-banner"><div className="page-width"><span className="overline">MY HAYAKUKI</span><h1>Good to see you,<br />{user.name.split(' ')[0]}.</h1><p>{user.tier} · Member since 2026</p></div></section><section className="account-content page-width"><aside className="profile-card"><div className="profile-avatar">{user.name.split(' ').map((part) => part[0]).join('').slice(0,2)}</div><h2>{user.name}</h2><p>{user.email}</p><div><span><UserRound /> Account type <strong>{user.role}</strong></span><span><MapPin /> Home airport <strong>{user.home}</strong></span><span><ShieldCheck /> Status <strong>Verified demo</strong></span></div><button><Settings /> Edit profile</button></aside><div className="account-main"><div className="account-stats"><article><TicketCheck /><strong>{bookings.filter((item) => item.status !== 'Cancelled').length}</strong><span>Upcoming trips</span></article><article><Heart /><strong>{saved.length}</strong><span>Saved flights</span></article><article><MapPin /><strong>3</strong><span>Places visited</span></article></div><div className="account-section-head"><div><span className="overline coral">YOUR SHORTLIST</span><h2>Saved flights</h2></div><Link to="/flights">Find more <ArrowRight /></Link></div>{savedFlights.length ? <div className="saved-flight-list">{savedFlights.map((flight) => <article key={flight.id}><span className="mini-airline" style={{ '--airline': flight.color }}>{flight.short}</span><div><strong>{flight.from} <ArrowRight /> {flight.to}</strong><small>{flight.airline} · {flight.depart}–{flight.arrive}</small></div><span>₹{flight.price.toLocaleString('en-IN')}</span><Link to="/flights">View</Link></article>)}</div> : <div className="empty-panel"><Heart /><h3>No saved flights yet</h3><p>Tap the heart on a flight to keep it here.</p></div>}</div></section></main>
}
